services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    command: python -u app/services/redis_consumer.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  test:
    build: .
    command: pytest --maxfail=1 --disable-warnings -q
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
